version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tictactoe-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01020304vV
      POSTGRES_DB: tictactoe
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: TicTacToe.Api/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tictactoe;Username=postgres;Password=postgres

volumes:
  db_data: